---
title: "Overview of Titanic Case Studies"
author: "Shannon Pileggi"
date: 2018-11-07
categories: ["R"]
tags: ["Titanic", "kaggle", "case studies"]
---

The ongoing [Kaggle Titanic competition](https://www.kaggle.com/c/titanic) asks the seemingly simple question, "Can you predict who survives?"  This series is intended to be **brief**, **digestible** posts on related but stand-alone topics that learners can use to up-level R code and get a deeper undertanding of various modeling techniques.  

Kaggle provides 3 data sets when you enroll in the competition:

* `train.csv` - 891 observations and 12 variables (_includes_ the survival outcome for for model training).
* `test.csv` - 418 observations and 11 variables (_excludes_ the survival outcome for for model testing).
*  `gender_submission.csv` - an example data set with 418 observations and 2 variables (passenger ID and surival prediction) to demonstrate the correct format for submission.
  
The idea here is that we use our `train` data set to create a model based on _supervised classification_, and then we use that model to generate survival predictions for the `test` data set.  When you submit your predictions, you automatically get a score that allows you to see how your model compares to other submissions!  However, since the Titanic data set is publicly available there are some rigged submissions with improbable results (1.0, ha!).  There are several Kaggle discussion posts on [what makes a good score](https://www.kaggle.com/c/titanic/discussion/26284), and a consensus seems to be that if you can hit 80-83\% then you are awesome!  

Because this data set is tried and true there are *many* publicly available [posts](https://towardsdatascience.com/how-i-got-a-score-of-82-3-and-ended-up-being-in-top-4-of-kaggles-titanic-dataset-bb2875cee6b5) about how to achieve that target, and I'm not a fan of duplicating efforts.  So please consider this series to be targeted to learning programming and modeling concepts, and not necessarily about squeezing out those last few percents.

