---
title: "Learning SQL through PostgreSQL in R"
author: "Shannon Pileggi"
date: 2018-10-26
categories: ["R"]
tags: ["PostgreSQL", "R"]
draft: true
---

# Overview

`SQL` is a hot keyword on so many data science job ads today.  If you didn't learn it as part of your curriculum or on the job, there are many online courses and materials that demonstrate the basics.  For deeper understanding, try creating your own project and _learn by doing_.  

# The (fictional) challenge

My daughter's daycare maintains awesome records of her activities throughout the day via an online ap (not fiction!).  Let's suppose there are multiple data entry mechanisms that inform on diaper change times:

1.  The diaper changing area links one table, `diaper`, with two relevant fields: 

- `staff_id` - The staff's unique identifier.
- `infant_id` - The infant's unique identifier. 
- `time_of_change` - A Unix timestamp in milliseconds representing when they changed the diaper

```
+------------------+--------------------------+
|      staffid     | time_of_change           |
+------------------+--------------------------+
| matt@example.com |            1534101377000 |
| eli@example.com  |                          |
+------------------+--------------------------+
```

2.  `activities`

# Getting started

R is rapidly expanding its infrastructure to connect with a variety of databases, and the [Databases using R](https://db.rstudio.com/) site is quite comprehensive.  For this demo, we'll use [PostgreSQL](https://www.postgresql.org/).  